### ISSUE TITLE
Wrong order among headers

### ISSUE THREAD

**Issue by mrzemoh** [telusdigital/tds-core#574]
## Description

* Wrong order among headers

## Reproduction Steps

* Go to https://tds.telus.com/components/index.html#flexgrid
* Look at headings. There are blocks which belong to level 4 parent but have headings level 3

## Reproduction Percentage (if applicable)

* 10/10 times

## Screenshots

* https://image.ibb.co/fwoYrc/Screenshot_1.png

**Comment by marcod1419** [comment]
Thanks for the issue report! Unfortunately, due to the way Styleguidist handles heading levels, it would take a disproportionate amount of work or compromise to fix this issue. However, one of our goals on our [roadmap](https://tds.telus.com/roadmap.html) is to create new docs, so this will no longer be an issue once that is implemented.
